/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Utilitarios.conexao;
import caixaDeTexto.limite;
import caixaDeTexto.limiteLetra;
import caixaDeTexto.limiteNumero;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Italo
 */
public class AlterarAluno extends java.awt.Dialog {
    conexao conecta = new conexao();
    conexao alconecta = new conexao();
    /**
     * Creates new form AlterarAluno3
     */
    public AlterarAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        
        jTextCod_Aluno.setEnabled(false);
        
        jComboBoxAlterar.removeAllItems();
        jComboBoxSexo_Aluno.removeAllItems();
        jComboBoxPeriodo_Aluno.removeAllItems();
        
        jComboBoxAlterar.addItem("Alterar");
        consultarNomes();
        
        jComboBoxSexo_Aluno.addItem("Masculino");
        jComboBoxSexo_Aluno.addItem("Feminino");
        jComboBoxSexo_Aluno.addItem("Outros");
        jComboBoxPeriodo_Aluno.addItem("Matutino");
        jComboBoxPeriodo_Aluno.addItem("Vespertino");
        jComboBoxPeriodo_Aluno.addItem("Noturno");
        
        jTextNome_Aluno.setDocument(new limiteLetra(40));
        jTextEndereco_Aluno.setDocument(new limite(40));
        jTextCurso_Aluno.setDocument(new limiteLetra(50));
        jTextMatricula_Aluno.setDocument(new limiteNumero(11));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxAlterar = new javax.swing.JComboBox<>();
        jLabelCod_Aluno = new javax.swing.JLabel();
        jTextCod_Aluno = new javax.swing.JTextField();
        jLabelNome_Aluno = new javax.swing.JLabel();
        jLabelCPF_Aluno = new javax.swing.JLabel();
        jLabelCelular_Aluno = new javax.swing.JLabel();
        jTextNome_Aluno = new javax.swing.JTextField();
        jFormattedTextFieldCPF_Aluno = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelular_Aluno = new javax.swing.JFormattedTextField();
        jLabelEndereço_Aluno = new javax.swing.JLabel();
        jTextEndereco_Aluno = new javax.swing.JTextField();
        jLabelMatricula_Aluno = new javax.swing.JLabel();
        jTextMatricula_Aluno = new javax.swing.JTextField();
        jLabelCurso_Aluno = new javax.swing.JLabel();
        jTextCurso_Aluno = new javax.swing.JTextField();
        jLabelSexo_Aluno = new javax.swing.JLabel();
        jComboBoxSexo_Aluno = new javax.swing.JComboBox<>();
        jLabelPeriodo_Aluno = new javax.swing.JLabel();
        jComboBoxPeriodo_Aluno = new javax.swing.JComboBox<>();
        jLabelNascimento_Aluno = new javax.swing.JLabel();
        jFormattedTextFieldNascimento_Aluno = new javax.swing.JFormattedTextField();
        jButtonVoltar = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabel1.setText("ALUNO A SER ALTERADO:");

        jComboBoxAlterar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxAlterarMouseClicked(evt);
            }
        });
        jComboBoxAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlterarActionPerformed(evt);
            }
        });

        jLabelCod_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCod_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelCod_Aluno.setText("COD:");
        jLabelCod_Aluno.setToolTipText("");
        jLabelCod_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextCod_Aluno.setText("             ");
        jTextCod_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCod_AlunoActionPerformed(evt);
            }
        });

        jLabelNome_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNome_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelNome_Aluno.setText("NOME:");
        jLabelNome_Aluno.setToolTipText("");
        jLabelNome_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelCPF_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCPF_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelCPF_Aluno.setText("CPF:");
        jLabelCPF_Aluno.setToolTipText("");
        jLabelCPF_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelCelular_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCelular_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelCelular_Aluno.setText("CELULAR:");
        jLabelCelular_Aluno.setToolTipText("");
        jLabelCelular_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextNome_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_AlunoActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCPF_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPF_AlunoActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCelular_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelEndereço_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEndereço_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelEndereço_Aluno.setText("ENDEREÇO:");
        jLabelEndereço_Aluno.setToolTipText("");
        jLabelEndereço_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextEndereco_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEndereco_AlunoActionPerformed(evt);
            }
        });

        jLabelMatricula_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMatricula_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelMatricula_Aluno.setText("Nª DE MATRÍCULA:");
        jLabelMatricula_Aluno.setToolTipText("");
        jLabelMatricula_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelCurso_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCurso_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelCurso_Aluno.setText("CURSO:");
        jLabelCurso_Aluno.setToolTipText("");
        jLabelCurso_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelSexo_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSexo_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelSexo_Aluno.setText("SEXO:");
        jLabelSexo_Aluno.setToolTipText("");
        jLabelSexo_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jComboBoxSexo_Aluno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxSexo_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexo_AlunoActionPerformed(evt);
            }
        });

        jLabelPeriodo_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPeriodo_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelPeriodo_Aluno.setText("PERÍODO:");
        jLabelPeriodo_Aluno.setToolTipText("");
        jLabelPeriodo_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jComboBoxPeriodo_Aluno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabelNascimento_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNascimento_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelNascimento_Aluno.setText("DATA DE NASCIMENTO:");
        jLabelNascimento_Aluno.setToolTipText("");
        jLabelNascimento_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldNascimento_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonVoltar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEndereço_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNome_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(316, 316, 316)
                                        .addComponent(jLabelCod_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextCod_Aluno, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                                    .addComponent(jTextEndereco_Aluno)
                                    .addComponent(jTextNome_Aluno))))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCelular_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldCelular_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldCPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextCurso_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMatricula_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNascimento_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUpdate)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCurso_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSexo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPeriodo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxSexo_Aluno, 0, 100, Short.MAX_VALUE)
                                    .addComponent(jComboBoxPeriodo_Aluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(200, 200, 200)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonVoltar)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextMatricula_Aluno)
                                    .addComponent(jFormattedTextFieldNascimento_Aluno, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(24, 24, 24))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBoxAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelCod_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextCod_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNome_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEndereço_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEndereco_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCelular_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCelular_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatricula_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMatricula_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNascimento_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldNascimento_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCurso_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSexo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextCurso_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSexo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPeriodo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPeriodo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVoltar)
                            .addComponent(jButtonUpdate))
                        .addContainerGap())))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(527, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jComboBoxAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlterarMouseClicked

    private void jComboBoxAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlterarActionPerformed
        if("Alterar".equals((String) jComboBoxAlterar.getSelectedItem())){
            jTextNome_Aluno.setText((String) jComboBoxAlterar.getSelectedItem());
            pegarDados();
            jButtonUpdate.setEnabled(false);
        } else {
            jComboBoxAlterar.removeItem("Alterar");
            jTextNome_Aluno.setText((String) jComboBoxAlterar.getSelectedItem());
            pegarDados();
            jButtonUpdate.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlterarActionPerformed

    private void jTextCod_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCod_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCod_AlunoActionPerformed

    private void jTextNome_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_AlunoActionPerformed

    private void jFormattedTextFieldCPF_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPF_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPF_AlunoActionPerformed

    private void jTextEndereco_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEndereco_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEndereco_AlunoActionPerformed

    private void jComboBoxSexo_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexo_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexo_AlunoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("update tbaluno set nome_aluno = ?, cpf_aluno = ? , data_de_nascimento_aluno = ?, celular_aluno = ?, endereco_aluno = ?, numero_de_matricula_aluno = ?, curso = ?, sexo = ?, periodo = ? where cod_aluno = ?");
            pst.setString(1, jTextNome_Aluno.getText());
            pst.setString(2, jFormattedTextFieldCPF_Aluno.getText());
            pst.setString(3, jFormattedTextFieldNascimento_Aluno.getText());
            pst.setString(4, jFormattedTextFieldCelular_Aluno.getText());
            pst.setString(5, jTextEndereco_Aluno.getText());
            pst.setString(6, jTextMatricula_Aluno.getText());
            pst.setString(7, jTextCurso_Aluno.getText());
            pst.setString(8, (String) jComboBoxSexo_Aluno.getSelectedItem());
            pst.setString(9, (String) jComboBoxPeriodo_Aluno.getSelectedItem());
            pst.setString(10, jTextCod_Aluno.getText());
            pst.executeUpdate();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao atualizar dados!\n Erro:" + ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public void consultarNomes(){
        conecta.executaSQL("select * from tbaluno order by cod_aluno");
        try {
            conecta.rs.first();
             do{
              jComboBoxAlterar.addItem(conecta.rs.getString("nome_aluno"));
        }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao procurar nomes já cadastrasdos!\nErro:" + ex);
        }
    }
    
    public void pegarDados(){
       alconecta.executaSQL("select * from tbaluno order by cod_aluno");     
        try {
            alconecta.rs.first();
             do{
                 if(jTextNome_Aluno.getText().equals((String) alconecta.rs.getString("nome_aluno"))){
                     jTextCurso_Aluno.setText((String) alconecta.rs.getString("curso"));
                     jTextCod_Aluno.setText(alconecta.rs.getString("cod_aluno"));
                     jTextEndereco_Aluno.setText((String) alconecta.rs.getString("endereco_aluno"));
                     jTextMatricula_Aluno.setText((String) alconecta.rs.getString("numero_de_matricula_aluno"));
                     jFormattedTextFieldCPF_Aluno.setText((String) alconecta.rs.getString("cpf_aluno"));
                     jFormattedTextFieldCelular_Aluno.setText((String) alconecta.rs.getString("celular_aluno"));
                     jFormattedTextFieldNascimento_Aluno.setText((String) alconecta.rs.getString("data_de_nascimento_aluno"));
                     jComboBoxPeriodo_Aluno.setSelectedItem((String) alconecta.rs.getString("periodo"));
                     jComboBoxSexo_Aluno.setSelectedItem((String) alconecta.rs.getString("sexo"));
                 }
            }while(alconecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher campos!\nErro:" + ex);
        }
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlterarAluno dialog = new AlterarAluno(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxAlterar;
    private javax.swing.JComboBox<String> jComboBoxPeriodo_Aluno;
    private javax.swing.JComboBox<String> jComboBoxSexo_Aluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF_Aluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular_Aluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimento_Aluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCPF_Aluno;
    private javax.swing.JLabel jLabelCelular_Aluno;
    private javax.swing.JLabel jLabelCod_Aluno;
    private javax.swing.JLabel jLabelCurso_Aluno;
    private javax.swing.JLabel jLabelEndereço_Aluno;
    private javax.swing.JLabel jLabelMatricula_Aluno;
    private javax.swing.JLabel jLabelNascimento_Aluno;
    private javax.swing.JLabel jLabelNome_Aluno;
    private javax.swing.JLabel jLabelPeriodo_Aluno;
    private javax.swing.JLabel jLabelSexo_Aluno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCod_Aluno;
    private javax.swing.JTextField jTextCurso_Aluno;
    private javax.swing.JTextField jTextEndereco_Aluno;
    private javax.swing.JTextField jTextMatricula_Aluno;
    private javax.swing.JTextField jTextNome_Aluno;
    // End of variables declaration//GEN-END:variables
     public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("escola.png")));
    }
}
