/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Utilitarios.ModeloTabela;
import Utilitarios.conexao;
import caixaDeTexto.limite;
import caixaDeTexto.limiteLetra;
import caixaDeTexto.limiteNumero;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Italo
 */
public class TelaAluno extends javax.swing.JFrame {
    conexao conecta = new conexao();
    conexao dadosconecta = new conexao();
    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
        setIcon();
        preencherTabela("select * from tbaluno order by cod_aluno");
        
        jTextNome_Aluno.setDocument(new limiteLetra(40));
        jTextEndereco_Aluno.setDocument(new limite(40));
        jTextCurso_Aluno.setDocument(new limiteLetra(50));
        jTextMatricula_Aluno.setDocument(new limiteNumero(11));
        
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        
        jTextCod_Aluno.setEnabled(false);
        jTextNome_Aluno.setEnabled(false);
        jFormattedTextFieldNascimento_Aluno.setEnabled(false);
        jFormattedTextFieldCelular_Aluno.setEnabled(false);
        jFormattedTextFieldCPF_Aluno.setEnabled(false);
        jTextEndereco_Aluno.setEnabled(false);
        jTextMatricula_Aluno.setEnabled(false);
        jTextCurso_Aluno.setEnabled(false);
        
        jComboBoxSexo_Aluno.setEnabled(false);
        jComboBoxPeriodo_Aluno.setEnabled(false);
        
        jComboBoxSexo_Aluno.removeAllItems();
        jComboBoxPeriodo_Aluno.removeAllItems();
        
        jComboBoxSexo_Aluno.addItem("Feminino");
        jComboBoxSexo_Aluno.addItem("Masculino");
        jComboBoxSexo_Aluno.addItem("Outros");
        
        jComboBoxPeriodo_Aluno.addItem("Matutino");
        jComboBoxPeriodo_Aluno.addItem("Vespertino");
        jComboBoxPeriodo_Aluno.addItem("Noturno");
        
        primeiro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Aluno = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonUltimo = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelCod_Aluno = new javax.swing.JLabel();
        jTextCod_Aluno = new javax.swing.JTextField();
        jTextNome_Aluno = new javax.swing.JTextField();
        jLabelNome_Aluno = new javax.swing.JLabel();
        jTextEndereco_Aluno = new javax.swing.JTextField();
        jLabelEndereço_Aluno = new javax.swing.JLabel();
        jLabelCPF_Aluno = new javax.swing.JLabel();
        jFormattedTextFieldCPF_Aluno = new javax.swing.JFormattedTextField();
        jLabelCelular_Aluno = new javax.swing.JLabel();
        jFormattedTextFieldCelular_Aluno = new javax.swing.JFormattedTextField();
        jLabelNascimento_Aluno1 = new javax.swing.JLabel();
        jFormattedTextFieldNascimento_Aluno = new javax.swing.JFormattedTextField();
        jTextMatricula_Aluno = new javax.swing.JTextField();
        jTextCurso_Aluno = new javax.swing.JTextField();
        jComboBoxPeriodo_Aluno = new javax.swing.JComboBox<>();
        jLabelMatricula_Aluno = new javax.swing.JLabel();
        jLabelCurso_Aluno = new javax.swing.JLabel();
        jLabelPeriodo_Aluno = new javax.swing.JLabel();
        jComboBoxSexo_Aluno = new javax.swing.JComboBox<>();
        jLabelSexo_Aluno = new javax.swing.JLabel();
        jButtonAtualizarTabela = new javax.swing.JButton();
        jButtonTabelaDeCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO - ALUNO");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.red);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1000, 800));
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo IFPA.jpg"))); // NOI18N

        jButtonVoltar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jTable_Aluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Aluno.getTableHeader().setReorderingAllowed(false);
        jTable_Aluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_AlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Aluno);
        if (jTable_Aluno.getColumnModel().getColumnCount() > 0) {
            jTable_Aluno.getColumnModel().getColumn(0).setResizable(false);
            jTable_Aluno.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable_Aluno.getColumnModel().getColumn(4).setResizable(false);
            jTable_Aluno.getColumnModel().getColumn(6).setResizable(false);
            jTable_Aluno.getColumnModel().getColumn(7).setResizable(false);
            jTable_Aluno.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTable_Aluno.getColumnModel().getColumn(8).setResizable(false);
            jTable_Aluno.getColumnModel().getColumn(8).setPreferredWidth(40);
        }

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificadores de Cadastro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButtonNovo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setText("NOVO");
        jButtonNovo.setToolTipText("F1");
        jButtonNovo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNovoMouseEntered(evt);
            }
        });
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jButtonNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonNovoKeyPressed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarKeyPressed(evt);
            }
        });

        jButtonAlterar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jButtonAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAlterarKeyPressed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de Dados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButtonUltimo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUltimo.setText("ULTIMO");
        jButtonUltimo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });
        jButtonUltimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonUltimoKeyPressed(evt);
            }
        });

        jButtonPrimeiro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPrimeiro.setText("PRIMEIRO");
        jButtonPrimeiro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonPrimeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPrimeiroMouseClicked(evt);
            }
        });
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });
        jButtonPrimeiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonPrimeiroKeyPressed(evt);
            }
        });

        jButtonAnterior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAnterior.setText("ANTERIOR");
        jButtonAnterior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProximo.setText("PROXIMO");
        jButtonProximo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Cadastro de Alunos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabelCod_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCod_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelCod_Aluno.setText("COD:");
        jLabelCod_Aluno.setToolTipText("");
        jLabelCod_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextCod_Aluno.setText("             ");

        jLabelNome_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNome_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelNome_Aluno.setText("NOME:");
        jLabelNome_Aluno.setToolTipText("");
        jLabelNome_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextEndereco_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEndereco_AlunoActionPerformed(evt);
            }
        });

        jLabelEndereço_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEndereço_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelEndereço_Aluno.setText("ENDEREÇO:");
        jLabelEndereço_Aluno.setToolTipText("");
        jLabelEndereço_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelCPF_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCPF_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelCPF_Aluno.setText("CPF:");
        jLabelCPF_Aluno.setToolTipText("");
        jLabelCPF_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldCPF_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCelular_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCelular_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelCelular_Aluno.setText("CELULAR:");
        jLabelCelular_Aluno.setToolTipText("");
        jLabelCelular_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldCelular_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelNascimento_Aluno1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNascimento_Aluno1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelNascimento_Aluno1.setText("DATA DE NASCIMENTO:");
        jLabelNascimento_Aluno1.setToolTipText("");
        jLabelNascimento_Aluno1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldNascimento_Aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNascimento_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNascimento_AlunoActionPerformed(evt);
            }
        });

        jComboBoxPeriodo_Aluno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabelMatricula_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMatricula_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelMatricula_Aluno.setText("Nª DE MATRÍCULA:");
        jLabelMatricula_Aluno.setToolTipText("");
        jLabelMatricula_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelCurso_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCurso_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelCurso_Aluno.setText("CURSO:");
        jLabelCurso_Aluno.setToolTipText("");
        jLabelCurso_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelPeriodo_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPeriodo_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelPeriodo_Aluno.setText("PERÍODO:");
        jLabelPeriodo_Aluno.setToolTipText("");
        jLabelPeriodo_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jComboBoxSexo_Aluno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxSexo_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexo_AlunoActionPerformed(evt);
            }
        });

        jLabelSexo_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSexo_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelSexo_Aluno.setText("SEXO:");
        jLabelSexo_Aluno.setToolTipText("");
        jLabelSexo_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelNome_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jTextNome_Aluno))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereço_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSexo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldCPF_Aluno)
                                .addGap(85, 85, 85)
                                .addComponent(jLabelMatricula_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jTextMatricula_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBoxSexo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextEndereco_Aluno)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jFormattedTextFieldCelular_Aluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCurso_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(jTextCurso_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelNascimento_Aluno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldNascimento_Aluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPeriodo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jComboBoxPeriodo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCelular_Aluno)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelCod_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)
                                .addComponent(jTextCod_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextCod_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNome_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelCod_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNome_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEndereco_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEndereço_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMatricula_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCPF_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMatricula_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCelular_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCurso_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCelular_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCurso_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNascimento_Aluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPeriodo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldNascimento_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPeriodo_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSexo_Aluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexo_Aluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAtualizarTabela.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAtualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtualizarTabela.setText("ATUALIZAR TABELA");
        jButtonAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarTabelaActionPerformed(evt);
            }
        });

        jButtonTabelaDeCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTabelaDeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTabelaDeCadastro.setText("TABELA DE CADASTRO");
        jButtonTabelaDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabelaDeCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabelLogo)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonTabelaDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAtualizarTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVoltar)
                .addGap(11, 11, 11))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelLogo)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTabelaDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAtualizarTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1002, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        Tela_Escolha tle = new Tela_Escolha();
        tle.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jComboBoxSexo_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexo_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexo_AlunoActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        novo();
        // TODO add your handling code here:   
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        salvar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextEndereco_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEndereco_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEndereco_AlunoActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonNovo.requestFocus();
        alterar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
            if(JOptionPane.showConfirmDialog (null, "Você tem certeza que deseja apagar o registro de\n"+ jTextCod_Aluno.getText() + "  " +  jTextNome_Aluno.getText() +"?","ATENÇÂO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                jButtonAnterior.setEnabled(false);
                jButtonProximo.setEnabled(false);
                excluir();
            }else{
                JOptionPane.showMessageDialog(null, "Exclusão Cancelada!");
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        jButtonProximo.setEnabled(true);
        anterior();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        jButtonAnterior.setEnabled(true);
        proximo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(false);
        ultimo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(true);
        primeiro();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jFormattedTextFieldNascimento_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNascimento_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNascimento_AlunoActionPerformed

    private void jTable_AlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_AlunoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_AlunoMouseClicked

    private void jButtonNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovoMouseEntered
        jButtonNovo.setBackground(new Color(235, 235, 235));
        jButtonNovo.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoMouseEntered

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        jButtonVoltar.setBackground(new Color(235, 235, 235));
        jButtonVoltar.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        jButtonVoltar.setBackground(new Color(0, 0, 0));
        jButtonVoltar.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNovoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            novo();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonUltimo.requestFocus();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonPrimeiro.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonVoltar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == evt.VK_F1)
                novo();
        else if(evt.getKeyCode() == evt.VK_F2)
                salvar();
        else if(evt.getKeyCode() == evt.VK_F3)
                alterar();
        else if(evt.getKeyCode() == evt.VK_F4)
                excluir();
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jButtonUltimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonUltimoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            ultimo();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonPrimeiro.requestFocus();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonNovo.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonVoltar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUltimoKeyPressed

    private void jButtonPrimeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrimeiroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrimeiroMouseClicked

    private void jButtonPrimeiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPrimeiroKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            primeiro();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonNovo.requestFocus();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonUltimo.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonVoltar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrimeiroKeyPressed

    private void jButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            salvar();
            jButtonNovo.requestFocus();
        if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonAlterar.requestFocus();
        if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonAlterar.requestFocus();
        if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonVoltar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarKeyPressed

    private void jButtonAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAlterarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            alterar();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonSalvar.requestFocus();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonSalvar.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonAtualizarTabela.requestFocus();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarKeyPressed

    private void jButtonAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarTabelaActionPerformed
        preencherTabela("select * from tbaluno order by cod_aluno");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtualizarTabelaActionPerformed

    private void jButtonTabelaDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabelaDeCadastroActionPerformed
        Tela_Tabela_Aluno tlta = new Tela_Tabela_Aluno();
        tlta.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTabelaDeCadastroActionPerformed
    private void jButtonNovoMouseExited(java.awt.event.MouseEvent evt) {                                        
        jButtonNovo.setBackground(new Color(0, 0, 0));
        jButtonNovo.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                       

    private void jButtonSalvarMouseExited(java.awt.event.MouseEvent evt) {                                          
        jButtonSalvar.setBackground(new Color(0, 0, 0));
        jButtonSalvar.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                         

    private void jButtonAlterarMouseEntered(java.awt.event.MouseEvent evt) {                                            
        jButtonAlterar.setBackground(new Color(235, 235, 235));
        jButtonAlterar.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }                                           

    private void jButtonExcluirMouseExited(java.awt.event.MouseEvent evt) {                                           
        jButtonExcluir.setBackground(new Color(0, 0, 0));
        jButtonExcluir.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                          

    private void jButtonUltimoMouseEntered(java.awt.event.MouseEvent evt) {                                           
        jButtonUltimo.setBackground(new Color(235, 235, 235));
        jButtonUltimo.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }                                          

    private void jButtonPrimeiroMouseExited(java.awt.event.MouseEvent evt) {                                            
        jButtonPrimeiro.setBackground(new Color(0, 0, 0));
        jButtonPrimeiro.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                           

    private void jButtonAnteriorMouseEntered(java.awt.event.MouseEvent evt) {                                             
        jButtonAnterior.setBackground(new Color(235, 235, 235));
        jButtonAnterior.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }                                            

    private void jButtonAnteriorMouseExited(java.awt.event.MouseEvent evt) {                                            
        jButtonAnterior.setBackground(new Color(0, 0, 0));
        jButtonAlterar.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                           

    private void jButtonProximoMouseEntered(java.awt.event.MouseEvent evt) {                                            
        jButtonExcluir.setBackground(new Color(235, 235, 235));
        jButtonExcluir.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }                                           

    private void jButtonProximoMouseExited(java.awt.event.MouseEvent evt) {                                           
        jButtonProximo.setBackground(new Color(0, 0, 0));
        jButtonProximo.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                          

    private void jButtonAtualizarTabelaMouseExited(java.awt.event.MouseEvent evt) {                                                   
        jButtonAtualizarTabela.setBackground(new Color(0, 0, 0));
        jButtonAtualizarTabela.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                                  

    private void jButtonSalvarMouseEntered(java.awt.event.MouseEvent evt) {                                           
        jButtonSalvar.setBackground(new Color(235, 235, 235));
        jButtonSalvar.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }                                          

    private void jButtonAlterarMouseExited(java.awt.event.MouseEvent evt) {                                           
        jButtonAlterar.setBackground(new Color(0, 0, 0));
        jButtonAlterar.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                          

    private void jButtonExcluirMouseEntered(java.awt.event.MouseEvent evt) {                                            
        jButtonExcluir.setBackground(new Color(235, 235, 235));
        jButtonExcluir.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }                                           

    private void jButtonUltimoMouseExited(java.awt.event.MouseEvent evt) {                                          
        jButtonUltimo.setBackground(new Color(0, 0, 0));
        jButtonUltimo.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }                                         

    private void jButtonPrimeiroMouseEntered(java.awt.event.MouseEvent evt) {                                             
        jButtonSalvar.setBackground(new Color(235, 235, 235));
        jButtonSalvar.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }                                            

    private void jButtonAtualizarTabelaMouseEntered(java.awt.event.MouseEvent evt) {                                                    
        jButtonAtualizarTabela.setBackground(new Color(235, 235, 235));
        jButtonAtualizarTabela.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }                                  
    
    /**
     * @param args the command line arguments
     */
        
    public  void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String[] colunas = new String[] {"   COD ", "                                  NOME ","NASCIMENTO", "           CPF",       "CELULAR", "                             ENDEREÇO ", "Nº DE MATRÍCULA ", "                                  CURSO ", "    SEXO ", " PERÍODO "};
        
       conecta.executaSQL(SQL);
        try{
            conecta.rs.first();
            do{ //Coloca os dados.
                dados.add(new Object[]{conecta.rs.getInt("cod_aluno"), conecta.rs.getString("nome_aluno"),conecta.rs.getString("data_de_nascimento_aluno"), conecta.rs.getString("cpf_aluno"), conecta.rs.getString("celular_aluno"), conecta.rs.getString("endereco_aluno"), conecta.rs.getString("numero_de_matricula_aluno"), conecta.rs.getString("curso"), conecta.rs.getString("sexo"), conecta.rs.getString("periodo")});
            }while (conecta.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!\nErro:" + ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
   
        jTable_Aluno.setModel(modelo);
        jTable_Aluno.getColumnModel().getColumn(0).setPreferredWidth(60);//cod_aluno
        jTable_Aluno.getColumnModel().getColumn(0).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(1).setPreferredWidth(250);///nome_aluno
        jTable_Aluno.getColumnModel().getColumn(1).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(2).setPreferredWidth(100);//data_de_nascimento_aluno
        jTable_Aluno.getColumnModel().getColumn(2).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(3).setPreferredWidth(100);//cpf_aluno
        jTable_Aluno.getColumnModel().getColumn(3).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(4).setPreferredWidth(100);//celular_aluno
        jTable_Aluno.getColumnModel().getColumn(4).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(5).setPreferredWidth(250);//endereco_aluno
        jTable_Aluno.getColumnModel().getColumn(5).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(6).setPreferredWidth(120);//numero_de_matricula_aluno
        jTable_Aluno.getColumnModel().getColumn(6).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(7).setPreferredWidth(250);//curso
        jTable_Aluno.getColumnModel().getColumn(7).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(8).setPreferredWidth(80);//sexo
        jTable_Aluno.getColumnModel().getColumn(8).setResizable(false);
        jTable_Aluno.getColumnModel().getColumn(9).setPreferredWidth(80);//periodo
        jTable_Aluno.getColumnModel().getColumn(9).setResizable(false);
        jTable_Aluno.getTableHeader().setReorderingAllowed(false);
        jTable_Aluno.setAutoResizeMode(jTable_Aluno.AUTO_RESIZE_OFF);
        jTable_Aluno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }   
    
    public void pegarDados(){
       dadosconecta.executaSQL("select * from tbaluno");     
        try {
            dadosconecta.rs.first();
            jTextNome_Aluno.setText((String) dadosconecta.rs.getString("nome_aluno"));
            jTextCurso_Aluno.setText((String) dadosconecta.rs.getString("curso"));
            jTextCod_Aluno.setText(dadosconecta.rs.getString("cod_aluno"));
            jTextEndereco_Aluno.setText((String) dadosconecta.rs.getString("endereco_aluno"));
            jTextMatricula_Aluno.setText((String) dadosconecta.rs.getString("numero_de_matricula_aluno"));
            jFormattedTextFieldCPF_Aluno.setText((String) dadosconecta.rs.getString("cpf_aluno"));
            jFormattedTextFieldCelular_Aluno.setText((String) dadosconecta.rs.getString("celular_aluno"));
            jFormattedTextFieldNascimento_Aluno.setText((String) dadosconecta.rs.getString("data_de_nascimento_aluno"));
            jComboBoxPeriodo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("periodo"));
            jComboBoxSexo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
        }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }
    
    private void novo(){
        
                preencherTabela("select * from tbaluno order by cod_aluno");

                jTextCod_Aluno.setText("");
                jTextNome_Aluno.setText("");
                jFormattedTextFieldCPF_Aluno.setText("");
                jFormattedTextFieldNascimento_Aluno.setText("");
                jFormattedTextFieldCelular_Aluno.setText("");
                jTextEndereco_Aluno.setText("");
                jTextMatricula_Aluno.setText("");
                jTextCurso_Aluno.setText("");

                jButtonNovo.setEnabled(false);
                jButtonAnterior.setEnabled(false);
                jButtonPrimeiro.setEnabled(false);
                jButtonProximo.setEnabled(false);
                jButtonUltimo.setEnabled(false);

                jButtonSalvar.setEnabled(true);
                jButtonAlterar.setEnabled(true);
                jButtonExcluir.setEnabled(false);

                jTextNome_Aluno.setEnabled(true);
                jFormattedTextFieldNascimento_Aluno.setEnabled(true);
                jFormattedTextFieldCelular_Aluno.setEnabled(true);
                jFormattedTextFieldCPF_Aluno.setEnabled(true);
                jTextEndereco_Aluno.setEnabled(true);
                jTextMatricula_Aluno.setEnabled(true);
                jTextCurso_Aluno.setEnabled(true);

                jComboBoxSexo_Aluno.setEnabled(true);
                jComboBoxPeriodo_Aluno.setEnabled(true);
                
    }
    
    private void salvar(){
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("insert into tbaluno(nome_aluno,data_de_nascimento_aluno,cpf_aluno,celular_aluno,endereco_aluno,numero_de_matricula_aluno,curso,sexo,periodo)values(?,?,?,?,?,?,?,?,?)");
            pst.setString(1, jTextNome_Aluno.getText());
            pst.setString(2, jFormattedTextFieldNascimento_Aluno.getText());
            pst.setString(3, jFormattedTextFieldCPF_Aluno.getText());
            pst.setString(4, jFormattedTextFieldCelular_Aluno.getText());
            pst.setString(5, jTextEndereco_Aluno.getText());
            pst.setString(6, jTextMatricula_Aluno.getText());
            pst.setString(7, jTextCurso_Aluno.getText());
            pst.setString(8, (String) jComboBoxSexo_Aluno.getSelectedItem());
            pst.setString(9, (String) jComboBoxPeriodo_Aluno.getSelectedItem());
            pst.execute();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao inserir dados!\n Erro:" + ex.getMessage());
        }
        
        preencherTabela("select * from tbaluno order by cod_aluno");
        
        jButtonNovo.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jButtonUltimo.setEnabled(true);
        
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextNome_Aluno.setEnabled(false);
        jFormattedTextFieldNascimento_Aluno.setEnabled(false);
        jFormattedTextFieldCelular_Aluno.setEnabled(false);
        jFormattedTextFieldCPF_Aluno.setEnabled(false);
        jTextEndereco_Aluno.setEnabled(false);
        jTextMatricula_Aluno.setEnabled(false);
        jTextCurso_Aluno.setEnabled(false);
        
        jComboBoxSexo_Aluno.setEnabled(false);
        jComboBoxPeriodo_Aluno.setEnabled(false);
        
    }
    
    private void alterar(){
        
        jButtonNovo.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jButtonUltimo.setEnabled(true);
        jButtonProximo.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextNome_Aluno.setEnabled(false);
        jFormattedTextFieldNascimento_Aluno.setEnabled(false);
        jFormattedTextFieldCelular_Aluno.setEnabled(false);
        jFormattedTextFieldCPF_Aluno.setEnabled(false);
        jTextEndereco_Aluno.setEnabled(false);
        jTextMatricula_Aluno.setEnabled(false);
        jTextCurso_Aluno.setEnabled(false);
        
        jComboBoxSexo_Aluno.setEnabled(false);
        jComboBoxPeriodo_Aluno.setEnabled(false); 
        
        AlterarAluno tla = new AlterarAluno(new javax.swing.JFrame(), true);
        tla.setVisible(true);        
    }
    
    private void excluir(){
              
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("delete from tbaluno where cod_aluno = ?");
            pst.setString(1, jTextCod_Aluno.getText());
            pst.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir dados!\n Erro:" + ex.getMessage());
        }
        
        //conecta.executaSQL("delete from tbaluno where nome_aluno='"+jTextNome_Aluno.getText()+"'");
        
        preencherTabela("select * from tbaluno order by cod_aluno");
        
        jButtonNovo.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jButtonProximo.setEnabled(true);
        jButtonUltimo.setEnabled(true);
        
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextNome_Aluno.setEnabled(false);
        jFormattedTextFieldNascimento_Aluno.setEnabled(false);
        jFormattedTextFieldCelular_Aluno.setEnabled(false);
        jFormattedTextFieldCPF_Aluno.setEnabled(false);
        jTextEndereco_Aluno.setEnabled(false);
        jTextMatricula_Aluno.setEnabled(false);
        jTextCurso_Aluno.setEnabled(false);
        
        jComboBoxSexo_Aluno.setEnabled(false);
        jComboBoxPeriodo_Aluno.setEnabled(false);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("escola.png")));
    }

    private void primeiro() {
        dadosconecta.executaSQL("select * from tbaluno");     
        try {
            dadosconecta.rs.first();
            jTextNome_Aluno.setText((String) dadosconecta.rs.getString("nome_aluno"));
            jTextCurso_Aluno.setText((String) dadosconecta.rs.getString("curso"));
            jTextCod_Aluno.setText(dadosconecta.rs.getString("cod_aluno"));
            jTextEndereco_Aluno.setText((String) dadosconecta.rs.getString("endereco_aluno"));
            jTextMatricula_Aluno.setText((String) dadosconecta.rs.getString("numero_de_matricula_aluno"));
            jFormattedTextFieldCPF_Aluno.setText((String) dadosconecta.rs.getString("cpf_aluno"));
            jFormattedTextFieldCelular_Aluno.setText((String) dadosconecta.rs.getString("celular_aluno"));
            jFormattedTextFieldNascimento_Aluno.setText((String) dadosconecta.rs.getString("data_de_nascimento_aluno"));
            jComboBoxPeriodo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("periodo"));
            jComboBoxSexo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
        }
    }

    private void ultimo() {
        dadosconecta.executaSQL("select * from tbaluno");     
        try {
            dadosconecta.rs.last();
            jTextNome_Aluno.setText((String) dadosconecta.rs.getString("nome_aluno"));
            jTextCurso_Aluno.setText((String) dadosconecta.rs.getString("curso"));
            jTextCod_Aluno.setText(dadosconecta.rs.getString("cod_aluno"));
            jTextEndereco_Aluno.setText((String) dadosconecta.rs.getString("endereco_aluno"));
            jTextMatricula_Aluno.setText((String) dadosconecta.rs.getString("numero_de_matricula_aluno"));
            jFormattedTextFieldCPF_Aluno.setText((String) dadosconecta.rs.getString("cpf_aluno"));
            jFormattedTextFieldCelular_Aluno.setText((String) dadosconecta.rs.getString("celular_aluno"));
            jFormattedTextFieldNascimento_Aluno.setText((String) dadosconecta.rs.getString("data_de_nascimento_aluno"));
            jComboBoxPeriodo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("periodo"));
            jComboBoxSexo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
        }
    }

    private void proximo() {
        jButtonExcluir.setEnabled(true);
        try {
            dadosconecta.rs.next();
            jTextNome_Aluno.setText((String) dadosconecta.rs.getString("nome_aluno"));
            jTextCurso_Aluno.setText((String) dadosconecta.rs.getString("curso"));
            jTextCod_Aluno.setText(dadosconecta.rs.getString("cod_aluno"));
            jTextEndereco_Aluno.setText((String) dadosconecta.rs.getString("endereco_aluno"));
            jTextMatricula_Aluno.setText((String) dadosconecta.rs.getString("numero_de_matricula_aluno"));
            jFormattedTextFieldCPF_Aluno.setText((String) dadosconecta.rs.getString("cpf_aluno"));
            jFormattedTextFieldCelular_Aluno.setText((String) dadosconecta.rs.getString("celular_aluno"));
            jFormattedTextFieldNascimento_Aluno.setText((String) dadosconecta.rs.getString("data_de_nascimento_aluno"));
            jComboBoxPeriodo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("periodo"));
            jComboBoxSexo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
            jButtonProximo.setEnabled(false);
        }
    }

    private void anterior() {
        jButtonExcluir.setEnabled(true);
        try {
            dadosconecta.rs.previous();
            jTextNome_Aluno.setText((String) dadosconecta.rs.getString("nome_aluno"));
            jTextCurso_Aluno.setText((String) dadosconecta.rs.getString("curso"));
            jTextCod_Aluno.setText(dadosconecta.rs.getString("cod_aluno"));
            jTextEndereco_Aluno.setText((String) dadosconecta.rs.getString("endereco_aluno"));
            jTextMatricula_Aluno.setText((String) dadosconecta.rs.getString("numero_de_matricula_aluno"));
            jFormattedTextFieldCPF_Aluno.setText((String) dadosconecta.rs.getString("cpf_aluno"));
            jFormattedTextFieldCelular_Aluno.setText((String) dadosconecta.rs.getString("celular_aluno"));
            jFormattedTextFieldNascimento_Aluno.setText((String) dadosconecta.rs.getString("data_de_nascimento_aluno"));
            jComboBoxPeriodo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("periodo"));
            jComboBoxSexo_Aluno.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
            jButtonAnterior.setEnabled(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAtualizarTabela;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonTabelaDeCadastro;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxPeriodo_Aluno;
    private javax.swing.JComboBox<String> jComboBoxSexo_Aluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF_Aluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular_Aluno;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimento_Aluno;
    private javax.swing.JLabel jLabelCPF_Aluno;
    private javax.swing.JLabel jLabelCelular_Aluno;
    private javax.swing.JLabel jLabelCod_Aluno;
    private javax.swing.JLabel jLabelCurso_Aluno;
    private javax.swing.JLabel jLabelEndereço_Aluno;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMatricula_Aluno;
    private javax.swing.JLabel jLabelNascimento_Aluno1;
    private javax.swing.JLabel jLabelNome_Aluno;
    private javax.swing.JLabel jLabelPeriodo_Aluno;
    private javax.swing.JLabel jLabelSexo_Aluno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Aluno;
    private javax.swing.JTextField jTextCod_Aluno;
    private javax.swing.JTextField jTextCurso_Aluno;
    private javax.swing.JTextField jTextEndereco_Aluno;
    private javax.swing.JTextField jTextMatricula_Aluno;
    private javax.swing.JTextField jTextNome_Aluno;
    // End of variables declaration//GEN-END:variables
}
