/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Utilitarios.conexao;
import caixaDeTexto.limite;
import caixaDeTexto.limiteLetra;
import caixaDeTexto.limiteNumero;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author Italo
 */
public class AlterarProfessor extends java.awt.Dialog {
    private conexao conecta = new conexao();
    private conexao alconecta = new conexao();
    private String nome;
    /**
     * Creates new form AlterarProfessor1
     */
    public AlterarProfessor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        this.setFocusableWindowState(true);
        
        jTextCod_Professor.setEnabled(false);
        
        jComboBoxAlterar.removeAllItems();
        jComboBoxSexo_Professor.removeAllItems();
        
        
        jComboBoxAlterar.addItem("Alterar");
        consultarNomes();
        pegarDados();
        
        jComboBoxSexo_Professor.addItem("Masculino");
        jComboBoxSexo_Professor.addItem("Feminino");
        jComboBoxSexo_Professor.addItem("Outros");
        
        jTextNome_Professor.setDocument(new limiteLetra(40));
        jTextEscolaridade_Professor.setDocument(new limiteLetra(20));
        jTextNaturalidade_Professor.setDocument(new limiteLetra(20));
        jTextEixo_de_Atuacao_Professor.setDocument(new limiteLetra(20));
        jTextEndereco_Professor.setDocument(new limite(40));
        jTextMatricula_Professor.setDocument(new limiteNumero(11));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxAlterar = new javax.swing.JComboBox<>();
        jLabelCod_Professor = new javax.swing.JLabel();
        jTextCod_Professor = new javax.swing.JTextField();
        jLabelNome_Professor = new javax.swing.JLabel();
        jLabelCPF_Professor = new javax.swing.JLabel();
        jLabelCelular_Professor = new javax.swing.JLabel();
        jTextNome_Professor = new javax.swing.JTextField();
        jFormattedTextFieldCPF_Professor = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelular_Professor = new javax.swing.JFormattedTextField();
        jLabelEndereço_Professor = new javax.swing.JLabel();
        jTextEndereco_Professor = new javax.swing.JTextField();
        jLabelMatricula_Professor = new javax.swing.JLabel();
        jTextMatricula_Professor = new javax.swing.JTextField();
        jLabeEscolaridade_Professor = new javax.swing.JLabel();
        jTextEscolaridade_Professor = new javax.swing.JTextField();
        jLabelSexo_Professor = new javax.swing.JLabel();
        jComboBoxSexo_Professor = new javax.swing.JComboBox<>();
        jLabelNascimento_Professor = new javax.swing.JLabel();
        jFormattedTextFieldNascimento_Professor = new javax.swing.JFormattedTextField();
        jButtonVoltar = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabelEixo_de_Atuacao_Professor = new javax.swing.JLabel();
        jTextEixo_de_Atuacao_Professor = new javax.swing.JTextField();
        jLabelSalario_Professor = new javax.swing.JLabel();
        jFormattedTextFieldSalario_Professor = new javax.swing.JFormattedTextField();
        jLabelNaturalidade_Professor = new javax.swing.JLabel();
        jTextNaturalidade_Professor = new javax.swing.JTextField();
        jLabelAno_de_Admissao_Professor = new javax.swing.JLabel();
        jFormattedTextFieldAno_de_Admissao_Professor = new javax.swing.JFormattedTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabel1.setText("PROFESSOR A SER ALTERADO:");

        jComboBoxAlterar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxAlterarMouseClicked(evt);
            }
        });
        jComboBoxAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlterarActionPerformed(evt);
            }
        });

        jLabelCod_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCod_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelCod_Professor.setText("COD:");
        jLabelCod_Professor.setToolTipText("");
        jLabelCod_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextCod_Professor.setText("             ");
        jTextCod_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCod_ProfessorActionPerformed(evt);
            }
        });

        jLabelNome_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelNome_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelNome_Professor.setText("NOME:");
        jLabelNome_Professor.setToolTipText("");
        jLabelNome_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelCPF_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCPF_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelCPF_Professor.setText("CPF:");
        jLabelCPF_Professor.setToolTipText("");
        jLabelCPF_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelCelular_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCelular_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelCelular_Professor.setText("CELULAR:");
        jLabelCelular_Professor.setToolTipText("");
        jLabelCelular_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextNome_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_ProfessorActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCPF_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPF_ProfessorActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCelular_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCelular_ProfessorActionPerformed(evt);
            }
        });

        jLabelEndereço_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelEndereço_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelEndereço_Professor.setText("ENDEREÇO:");
        jLabelEndereço_Professor.setToolTipText("");
        jLabelEndereço_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextEndereco_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEndereco_ProfessorActionPerformed(evt);
            }
        });

        jLabelMatricula_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelMatricula_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelMatricula_Professor.setText("Nª DE MATRÍCULA:");
        jLabelMatricula_Professor.setToolTipText("");
        jLabelMatricula_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabeEscolaridade_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabeEscolaridade_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabeEscolaridade_Professor.setText("ESCOLARIDADE:");
        jLabeEscolaridade_Professor.setToolTipText("");
        jLabeEscolaridade_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelSexo_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSexo_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelSexo_Professor.setText("SEXO:");
        jLabelSexo_Professor.setToolTipText("");
        jLabelSexo_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jComboBoxSexo_Professor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxSexo_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexo_ProfessorActionPerformed(evt);
            }
        });

        jLabelNascimento_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelNascimento_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelNascimento_Professor.setText("DATA DE NASCIMENTO:");
        jLabelNascimento_Professor.setToolTipText("");
        jLabelNascimento_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldNascimento_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonVoltar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jButtonUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonUpdateKeyPressed(evt);
            }
        });

        jLabelEixo_de_Atuacao_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelEixo_de_Atuacao_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelEixo_de_Atuacao_Professor.setText("EIXO DE ATUAÇÃO:");
        jLabelEixo_de_Atuacao_Professor.setToolTipText("");
        jLabelEixo_de_Atuacao_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextEixo_de_Atuacao_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEixo_de_Atuacao_ProfessorActionPerformed(evt);
            }
        });

        jLabelSalario_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSalario_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelSalario_Professor.setText("SALÁRIO:");
        jLabelSalario_Professor.setToolTipText("");
        jLabelSalario_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldSalario_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$: ##.###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelNaturalidade_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelNaturalidade_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelNaturalidade_Professor.setText("NATURALIDADE:");
        jLabelNaturalidade_Professor.setToolTipText("");
        jLabelNaturalidade_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelAno_de_Admissao_Professor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelAno_de_Admissao_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 10)); // NOI18N
        jLabelAno_de_Admissao_Professor.setText("ANO DE ADMISSÃO:");
        jLabelAno_de_Admissao_Professor.setToolTipText("");
        jLabelAno_de_Admissao_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldAno_de_Admissao_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelNome_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEndereço_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCod_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCod_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextNome_Professor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(jTextEndereco_Professor))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelEixo_de_Atuacao_Professor)
                                .addComponent(jLabelAno_de_Admissao_Professor))
                            .addComponent(jLabeEscolaridade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCPF_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFormattedTextFieldCPF_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldCelular_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEscolaridade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEixo_de_Atuacao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldAno_de_Admissao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelCelular_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNascimento_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNaturalidade_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldNascimento_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNaturalidade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonVoltar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSexo_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSalario_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelMatricula_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxSexo_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldSalario_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextMatricula_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(1, 1, 1)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCod_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCod_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNome_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEndereço_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEndereco_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNascimento_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldNascimento_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNaturalidade_Professor)
                            .addComponent(jLabelNaturalidade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatricula_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMatricula_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSalario_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldSalario_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSexo_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSexo_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCPF_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCPF_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCelular_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCelular_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeEscolaridade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEscolaridade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelEixo_de_Atuacao_Professor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextEixo_de_Atuacao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAno_de_Admissao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldAno_de_Admissao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonVoltar))
                .addGap(12, 12, 12))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(517, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jComboBoxAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlterarMouseClicked

    private void jComboBoxAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlterarActionPerformed
        if("Alterar".equals((String) jComboBoxAlterar.getSelectedItem())){
            jButtonUpdate.setEnabled(false);
            nome = (String) jComboBoxAlterar.getSelectedItem();
            nome = nome.replaceAll("[^aA-zZ]", "");
            jTextNome_Professor.setText(nome);
            pegarDados();
        }else{
            jButtonUpdate.setEnabled(true);
            jComboBoxAlterar.removeItem("Alterar");
            jTextNome_Professor.setText((String) jComboBoxAlterar.getSelectedItem());
            pegarDados();
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlterarActionPerformed

    private void jTextCod_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCod_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCod_ProfessorActionPerformed

    private void jTextNome_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_ProfessorActionPerformed

    private void jFormattedTextFieldCPF_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPF_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPF_ProfessorActionPerformed

    private void jFormattedTextFieldCelular_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelular_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCelular_ProfessorActionPerformed

    private void jTextEndereco_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEndereco_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEndereco_ProfessorActionPerformed

    private void jComboBoxSexo_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexo_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexo_ProfessorActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("update tbprofessor set nome_prof = ?,data_de_nascimento_prof = ?,cpf_prof = ?,celular_prof = ?,endereco_prof = ?,numero_de_matricula_prof = ?,escolaridade = ?,salario = ?,admissao = ?,naturalidade = ?,eixo_de_atuacao = ?,sexo = ? where cod_prof  = ?");
            pst.setString(1, jTextNome_Professor.getText());
            pst.setString(2, jFormattedTextFieldNascimento_Professor.getText());
            pst.setString(3, jFormattedTextFieldCPF_Professor.getText());
            pst.setString(4, jFormattedTextFieldCelular_Professor.getText());
            pst.setString(5, jTextEndereco_Professor.getText());
            pst.setString(6, jTextMatricula_Professor.getText());
            pst.setString(7, jTextEscolaridade_Professor.getText());
            pst.setString(8, jFormattedTextFieldSalario_Professor.getText());
            pst.setString(9, jFormattedTextFieldAno_de_Admissao_Professor.getText());
            pst.setString(10, jTextNaturalidade_Professor.getText());
            pst.setString(11, jTextEixo_de_Atuacao_Professor.getText());
            pst.setString(12, (String) jComboBoxSexo_Professor.getSelectedItem());
            pst.setString(13, jTextCod_Professor.getText());
            pst.executeUpdate();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao atualizar dados!\n Erro:" + ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonUpdateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateKeyPressed

    private void jTextEixo_de_Atuacao_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEixo_de_Atuacao_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEixo_de_Atuacao_ProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    
     public void consultarNomes(){
        conecta.executaSQL("select * from tbprofessor order by cod_prof");
        try {
            conecta.rs.first();
             do{
              jComboBoxAlterar.addItem("(" + conecta.rs.getInt("cod_prof")+ ")" + " - " + conecta.rs.getString("nome_prof"));
        }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao procurar nomes já cadastrasdos!\nErro:" + ex);
        }
    }
    
    public void pegarDados(){
       alconecta.executaSQL("select * from tbprofessor order by cod_prof");
       
        try {
            alconecta.rs.first();
             do{
                 if(jTextNome_Professor.getText().equals("(" + ")" + " - " + (String) alconecta.rs.getString("nome_prof"))){
                     jTextNome_Professor.setText((String) alconecta.rs.getString("nome_prof"));
                     jTextEixo_de_Atuacao_Professor.setText(alconecta.rs.getString("eixo_de_atuacao"));
                     jTextCod_Professor.setText(alconecta.rs.getString("cod_prof"));
                     jTextEndereco_Professor.setText((String) alconecta.rs.getString("endereco_prof"));
                     jTextMatricula_Professor.setText((String) alconecta.rs.getString("numero_de_matricula_prof"));
                     jTextNaturalidade_Professor.setText(alconecta.rs.getString("naturalidade"));
                     jTextEscolaridade_Professor.setText(alconecta.rs.getString("escolaridade"));
                     jFormattedTextFieldAno_de_Admissao_Professor.setText(alconecta.rs.getString("admissao"));
                     jFormattedTextFieldCPF_Professor.setText((String) alconecta.rs.getString("cpf_prof"));
                     jFormattedTextFieldCelular_Professor.setText((String) alconecta.rs.getString("celular_prof"));
                     jFormattedTextFieldNascimento_Professor.setText((String) alconecta.rs.getString("data_de_nascimento_prof"));
                     jFormattedTextFieldSalario_Professor.setText(alconecta.rs.getString("salario"));
                     jComboBoxSexo_Professor.setSelectedItem((String) alconecta.rs.getString("sexo"));
                 }
            }while(alconecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
        }
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlterarProfessor dialog = new AlterarProfessor(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    //jTextNome_Aluno.setText((String) jComboBoxAlterar.getSelectedItem());
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxAlterar;
    private javax.swing.JComboBox<String> jComboBoxSexo_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldAno_de_Admissao_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimento_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldSalario_Professor;
    private javax.swing.JLabel jLabeEscolaridade_Professor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAno_de_Admissao_Professor;
    private javax.swing.JLabel jLabelCPF_Professor;
    private javax.swing.JLabel jLabelCelular_Professor;
    private javax.swing.JLabel jLabelCod_Professor;
    private javax.swing.JLabel jLabelEixo_de_Atuacao_Professor;
    private javax.swing.JLabel jLabelEndereço_Professor;
    private javax.swing.JLabel jLabelMatricula_Professor;
    private javax.swing.JLabel jLabelNascimento_Professor;
    private javax.swing.JLabel jLabelNaturalidade_Professor;
    private javax.swing.JLabel jLabelNome_Professor;
    private javax.swing.JLabel jLabelSalario_Professor;
    private javax.swing.JLabel jLabelSexo_Professor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCod_Professor;
    private javax.swing.JTextField jTextEixo_de_Atuacao_Professor;
    private javax.swing.JTextField jTextEndereco_Professor;
    private javax.swing.JTextField jTextEscolaridade_Professor;
    private javax.swing.JTextField jTextMatricula_Professor;
    private javax.swing.JTextField jTextNaturalidade_Professor;
    private javax.swing.JTextField jTextNome_Professor;
    // End of variables declaration//GEN-END:variables
     public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("escola.png")));
    }
}
