/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Utilitarios.ModeloTabela;
import Utilitarios.conexao;
import caixaDeTexto.limite;
import caixaDeTexto.limiteLetra;
import caixaDeTexto.limiteNumero;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Italo
 */
public class TelaProfessor extends javax.swing.JFrame {
    conexao conecta = new conexao();
    conexao dadosconecta = new conexao();
    /**
     * Creates new form TelaAluno
     */
    public TelaProfessor() {
        initComponents();
        setIcon();
        preencherTabela("select * from tbprofessor order by cod_prof");
        
        jTextNome_Professor.setDocument(new limiteLetra(40));
        jTextMatricula_Professor.setDocument(new limiteNumero(11));
        jTextEscolaridade_Professor.setDocument(new limiteLetra(20));
        jTextNaturalidade_Professor.setDocument(new limiteLetra(20));
        jTextEixo_de_Atuacao_Professor.setDocument(new limiteLetra(20));
        jTextEndereco_Professor.setDocument(new limite(40));
        
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        
        jTextCod_Professor.setEnabled(false);
        jTextMatricula_Professor.setEnabled(false);
        jFormattedTextFieldCPF_Professor.setEnabled(false);
        jFormattedTextFieldSalario_Professor.setEnabled(false);
        jTextEndereco_Professor.setEnabled(false);
        jTextNome_Professor.setEnabled(false);
        jTextEixo_de_Atuacao_Professor.setEnabled(false);
        
        jComboBoxSexo_Professor.setEnabled(false);
       
        jFormattedTextFieldCelular_Professor.setEnabled(false);
        jFormattedTextFieldSalario_Professor.setEnabled(false);
        jFormattedTextFieldNascimento_Professor.setEnabled(false);
        jFormattedTextFieldAno_de_Admissao_Professor.setEnabled(false);
        jTextEscolaridade_Professor.setEnabled(false);
        jTextNaturalidade_Professor.setEnabled(false);
        
        jComboBoxSexo_Professor.removeAllItems(); 
        
        jComboBoxSexo_Professor.addItem("Feminino");
        jComboBoxSexo_Professor.addItem("Masculino");
        jComboBoxSexo_Professor.addItem("Outros");
        
        primeiro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextEscolaridade_Professor1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Professor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonUltimo = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelCod_Professor = new javax.swing.JLabel();
        jTextCod_Professor = new javax.swing.JTextField();
        jLabelNome_Aluno = new javax.swing.JLabel();
        jTextMatricula_Professor = new javax.swing.JTextField();
        jLabelCPF_Professor = new javax.swing.JLabel();
        jFormattedTextFieldCPF_Professor = new javax.swing.JFormattedTextField();
        jLabelCelular_Professor = new javax.swing.JLabel();
        jFormattedTextFieldCelular_Professor = new javax.swing.JFormattedTextField();
        jTextNaturalidade_Professor = new javax.swing.JTextField();
        jLabelNaturalidade_Professor = new javax.swing.JLabel();
        jLabelEndereço_Professor = new javax.swing.JLabel();
        jTextEndereco_Professor = new javax.swing.JTextField();
        jLabelMatricula_Professor = new javax.swing.JLabel();
        jTextNome_Professor = new javax.swing.JTextField();
        jLabelSalario_Professor = new javax.swing.JLabel();
        jFormattedTextFieldSalario_Professor = new javax.swing.JFormattedTextField();
        jLabelAno_de_Admissao_Professor = new javax.swing.JLabel();
        jFormattedTextFieldAno_de_Admissao_Professor = new javax.swing.JFormattedTextField();
        jLabelEixo_de_Atuacao_Professor = new javax.swing.JLabel();
        jTextEixo_de_Atuacao_Professor = new javax.swing.JTextField();
        jLabelNascimento_Professor = new javax.swing.JLabel();
        jFormattedTextFieldNascimento_Professor = new javax.swing.JFormattedTextField();
        jLabelSexo_Professor = new javax.swing.JLabel();
        jComboBoxSexo_Professor = new javax.swing.JComboBox<>();
        jLabelEscolaridade_Professor = new javax.swing.JLabel();
        jTextEscolaridade_Professor = new javax.swing.JTextField();
        jButtonTabelaDeCadastro = new javax.swing.JButton();
        jButtonAtualizarTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO - PROFESSOR");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.red);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1000, 800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo IFPA.jpg"))); // NOI18N

        jButtonVoltar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jTable_Professor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Professor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_Professor);
        if (jTable_Professor.getColumnModel().getColumnCount() > 0) {
            jTable_Professor.getColumnModel().getColumn(0).setResizable(false);
            jTable_Professor.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable_Professor.getColumnModel().getColumn(4).setResizable(false);
            jTable_Professor.getColumnModel().getColumn(6).setResizable(false);
            jTable_Professor.getColumnModel().getColumn(7).setResizable(false);
            jTable_Professor.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTable_Professor.getColumnModel().getColumn(8).setResizable(false);
            jTable_Professor.getColumnModel().getColumn(8).setPreferredWidth(40);
        }

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificadores de Cadastro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButtonNovo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setText("NOVO");
        jButtonNovo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNovoMouseExited(evt);
            }
        });
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jButtonNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonNovoKeyPressed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseExited(evt);
            }
        });
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSalvarKeyPressed(evt);
            }
        });

        jButtonAlterar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAlterarMouseExited(evt);
            }
        });
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jButtonAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAlterarKeyPressed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonExcluirMouseExited(evt);
            }
        });
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jButtonExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonExcluirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de Dados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jButtonUltimo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUltimo.setText("ULTIMO");
        jButtonUltimo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonUltimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUltimoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUltimoMouseExited(evt);
            }
        });
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });
        jButtonUltimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonUltimoKeyPressed(evt);
            }
        });

        jButtonPrimeiro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPrimeiro.setText("PRIMEIRO");
        jButtonPrimeiro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonPrimeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPrimeiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPrimeiroMouseExited(evt);
            }
        });
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });
        jButtonPrimeiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonPrimeiroKeyPressed(evt);
            }
        });

        jButtonAnterior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAnterior.setText("ANTERIOR");
        jButtonAnterior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAnteriorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAnteriorMouseExited(evt);
            }
        });
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProximo.setText("PROXIMO");
        jButtonProximo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButtonProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonProximoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonProximoMouseExited(evt);
            }
        });
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Cadastro de Professores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Letter Gothic", 1, 11))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCod_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCod_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelCod_Professor.setText("COD:");
        jLabelCod_Professor.setToolTipText("");
        jLabelCod_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextCod_Professor.setText("             ");

        jLabelNome_Aluno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNome_Aluno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelNome_Aluno.setText("NOME:");
        jLabelNome_Aluno.setToolTipText("");
        jLabelNome_Aluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelCPF_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCPF_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelCPF_Professor.setText("CPF:");
        jLabelCPF_Professor.setToolTipText("");
        jLabelCPF_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldCPF_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCelular_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCelular_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelCelular_Professor.setText("CELULAR:");
        jLabelCelular_Professor.setToolTipText("");
        jLabelCelular_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldCelular_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelular_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCelular_ProfessorActionPerformed(evt);
            }
        });

        jLabelNaturalidade_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNaturalidade_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelNaturalidade_Professor.setText("NATURALIDADE:");
        jLabelNaturalidade_Professor.setToolTipText("");
        jLabelNaturalidade_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelEndereço_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEndereço_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelEndereço_Professor.setText("ENDEREÇO:");
        jLabelEndereço_Professor.setToolTipText("");
        jLabelEndereço_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextEndereco_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEndereco_ProfessorActionPerformed(evt);
            }
        });

        jLabelMatricula_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMatricula_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelMatricula_Professor.setText("Nª DE MATRÍCULA:");
        jLabelMatricula_Professor.setToolTipText("");
        jLabelMatricula_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTextNome_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_ProfessorActionPerformed(evt);
            }
        });

        jLabelSalario_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalario_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelSalario_Professor.setText("SALÁRIO:");
        jLabelSalario_Professor.setToolTipText("");
        jLabelSalario_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldSalario_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$: ##.###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelAno_de_Admissao_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAno_de_Admissao_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelAno_de_Admissao_Professor.setText("ANO DE ADMISSÃO:");
        jLabelAno_de_Admissao_Professor.setToolTipText("");
        jLabelAno_de_Admissao_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldAno_de_Admissao_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelEixo_de_Atuacao_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEixo_de_Atuacao_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelEixo_de_Atuacao_Professor.setText("EIXO DE ATUAÇÃO:");
        jLabelEixo_de_Atuacao_Professor.setToolTipText("");
        jLabelEixo_de_Atuacao_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelNascimento_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNascimento_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelNascimento_Professor.setText("DATA DE NASCIMENTO:");
        jLabelNascimento_Professor.setToolTipText("");
        jLabelNascimento_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        try {
            jFormattedTextFieldNascimento_Professor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelSexo_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSexo_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelSexo_Professor.setText("SEXO:");
        jLabelSexo_Professor.setToolTipText("");
        jLabelSexo_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jComboBoxSexo_Professor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxSexo_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexo_ProfessorActionPerformed(evt);
            }
        });

        jLabelEscolaridade_Professor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEscolaridade_Professor.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelEscolaridade_Professor.setText("ESCOLARIDADE:");
        jLabelEscolaridade_Professor.setToolTipText("");
        jLabelEscolaridade_Professor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereço_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCelular_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCPF_Professor)
                            .addComponent(jLabelNome_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCod_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextFieldCPF_Professor, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldCelular_Professor)
                                    .addComponent(jTextCod_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNaturalidade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEscolaridade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextEscolaridade_Professor, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jTextNaturalidade_Professor)))
                            .addComponent(jTextEndereco_Professor)
                            .addComponent(jTextNome_Professor))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSexo_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelMatricula_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextMatricula_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelEixo_de_Atuacao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxSexo_Professor, 0, 202, Short.MAX_VALUE)
                                    .addComponent(jTextEixo_de_Atuacao_Professor))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAno_de_Admissao_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNascimento_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSalario_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldAno_de_Admissao_Professor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFormattedTextFieldNascimento_Professor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFormattedTextFieldSalario_Professor, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCod_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCod_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNome_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNome_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jFormattedTextFieldCPF_Professor)
                        .addComponent(jLabelCPF_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextNaturalidade_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNaturalidade_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCelular_Professor, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldCelular_Professor)
                            .addComponent(jLabelEscolaridade_Professor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextEndereco_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEndereço_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextMatricula_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMatricula_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNascimento_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEixo_de_Atuacao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextEixo_de_Atuacao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelAno_de_Admissao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabelSexo_Professor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBoxSexo_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jFormattedTextFieldSalario_Professor)
                                                .addComponent(jLabelSalario_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jFormattedTextFieldAno_de_Admissao_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jFormattedTextFieldNascimento_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextEscolaridade_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonTabelaDeCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTabelaDeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTabelaDeCadastro.setText("TABELA DE CADASTRO");
        jButtonTabelaDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabelaDeCadastroActionPerformed(evt);
            }
        });

        jButtonAtualizarTabela.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAtualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtualizarTabela.setText("ATUALIZAR TABELA");
        jButtonAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabelLogo)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTabelaDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAtualizarTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVoltar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogo)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTabelaDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAtualizarTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(994, 593));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        Tela_Escolha tle = new Tela_Escolha();
        tle.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jComboBoxSexo_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexo_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSexo_ProfessorActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        novo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        salvar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextEndereco_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEndereco_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEndereco_ProfessorActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        jButtonNovo.requestFocus();
        alterar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
            if(JOptionPane.showConfirmDialog (null, "Você tem certeza que deseja apagar o registro de \n"+ jTextCod_Professor.getText() +"  " +jTextNome_Professor.getText() + "?","ATENÇÂO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                jButtonAnterior.setEnabled(false);
                jButtonProximo.setEnabled(false);
                excluir();
            }else{
                JOptionPane.showMessageDialog(null, "Exclusão Cancelada!");
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jFormattedTextFieldCelular_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCelular_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCelular_ProfessorActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonProximo.setEnabled(false);
        ultimo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        jButtonExcluir.setEnabled(true);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(true);
        primeiro();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        jButtonProximo.setEnabled(true);
        anterior();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        jButtonAnterior.setEnabled(true);
        proximo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovoMouseExited
//        jButtonNovo.setBackground(new Color(0, 0, 0));
//        jButtonNovo.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoMouseExited

    private void jButtonSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseExited
//        jButtonSalvar.setBackground(new Color(0, 0, 0));
//        jButtonSalvar.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarMouseExited

    private void jButtonAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlterarMouseEntered
//        jButtonAlterar.setBackground(new Color(235, 235, 235));
//        jButtonAlterar.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarMouseEntered

    private void jButtonExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirMouseExited
//        jButtonExcluir.setBackground(new Color(0, 0, 0));
//        jButtonExcluir.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirMouseExited

    private void jButtonUltimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUltimoMouseEntered
//        jButtonUltimo.setBackground(new Color(235, 235, 235));
//        jButtonUltimo.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUltimoMouseEntered

    private void jButtonPrimeiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrimeiroMouseExited
//        jButtonPrimeiro.setBackground(new Color(0, 0, 0));
//        jButtonPrimeiro.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrimeiroMouseExited

    private void jButtonAnteriorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseEntered
//        jButtonAnterior.setBackground(new Color(235, 235, 235));
//        jButtonAnterior.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnteriorMouseEntered

    private void jButtonAnteriorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseExited
//        jButtonAnterior.setBackground(new Color(0, 0, 0));
//        jButtonAlterar.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnteriorMouseExited

    private void jButtonProximoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProximoMouseEntered
//        jButtonExcluir.setBackground(new Color(235, 235, 235));
//        jButtonExcluir.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoMouseEntered

    private void jButtonProximoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProximoMouseExited
//        jButtonProximo.setBackground(new Color(0, 0, 0));
//        jButtonProximo.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoMouseExited

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        jButtonVoltar.setBackground(new Color(0, 0, 0));
        jButtonVoltar.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovoMouseEntered
//        jButtonNovo.setBackground(new Color(235, 235, 235));
//        jButtonNovo.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoMouseEntered

    private void jButtonSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseEntered
//        jButtonSalvar.setBackground(new Color(235, 235, 235));
//        jButtonSalvar.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarMouseEntered

    private void jButtonAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlterarMouseExited
//        jButtonAlterar.setBackground(new Color(0, 0, 0));
//        jButtonAlterar.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarMouseExited

    private void jButtonExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirMouseEntered
//        jButtonExcluir.setBackground(new Color(235, 235, 235));
//        jButtonExcluir.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirMouseEntered

    private void jButtonUltimoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUltimoMouseExited
//        jButtonUltimo.setBackground(new Color(0, 0, 0));
//        jButtonUltimo.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUltimoMouseExited

    private void jButtonPrimeiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrimeiroMouseEntered
//        jButtonSalvar.setBackground(new Color(235, 235, 235));
//        jButtonSalvar.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrimeiroMouseEntered

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        jButtonVoltar.setBackground(new Color(235, 235, 235));
        jButtonVoltar.setForeground(new Color(58, 65, 84));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonNovoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNovoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            novo();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonUltimo.requestFocus();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonPrimeiro.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonVoltar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoKeyPressed

    private void jButtonSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSalvarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            salvar();
            jButtonNovo.requestFocus();
        if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonAlterar.requestFocus();
        if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonAlterar.requestFocus();
        if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonVoltar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarKeyPressed

    private void jButtonAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAlterarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            alterar();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonSalvar.requestFocus();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonSalvar.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonAtualizarTabela.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarKeyPressed

    private void jButtonExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonExcluirKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            excluir();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonAlterar.requestFocus();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonSalvar.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonAtualizarTabela.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirKeyPressed

    private void jButtonUltimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonUltimoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            ultimo();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonPrimeiro.requestFocus();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonNovo.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonVoltar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUltimoKeyPressed

    private void jButtonPrimeiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPrimeiroKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
            primeiro();
        else if(evt.getKeyCode() == evt.VK_RIGHT)
                jButtonNovo.requestFocus();
        else if(evt.getKeyCode() == evt.VK_LEFT)
                jButtonUltimo.requestFocus();
        else if(evt.getKeyCode() == evt.VK_DOWN)
                jButtonVoltar.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrimeiroKeyPressed

    private void jButtonTabelaDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabelaDeCadastroActionPerformed
        Tela_Tabela_Professor tltp = new Tela_Tabela_Professor();
        tltp.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTabelaDeCadastroActionPerformed

    private void jButtonAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarTabelaActionPerformed
        preencherTabela("select * from tbprofessor order by cod_prof");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtualizarTabelaActionPerformed

    private void jTextNome_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_ProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
        
    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String[] colunas = new String[] {"   COD ", "                                  NOME ","NASCIMENTO", "           CPF", "    CELULAR", "                             ENDEREÇO ", "Nº DE MATRÍCULA ","ESCOLARIDADE","      SALARIO","ANO DE ADMISSÃO","NATURALIDADE","                        EIXO DE ATUAÇÃO", "    SEXO"};
        
       conecta.executaSQL(SQL);
        try{
            conecta.rs.first();
            do{ //Coloca os dados.
                dados.add(new Object[]{conecta.rs.getInt("cod_prof"), conecta.rs.getString("nome_prof"), conecta.rs.getString("data_de_nascimento_prof"),conecta.rs.getString("cpf_prof"), conecta.rs.getString("celular_prof"), conecta.rs.getString("endereco_prof"), conecta.rs.getString("numero_de_matricula_prof"), conecta.rs.getString("escolaridade"), conecta.rs.getString("salario"), conecta.rs.getString("admissao"),conecta.rs.getString("naturalidade"),conecta.rs.getString("eixo_de_atuacao"),conecta.rs.getString("sexo")});
            }while (conecta.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!\nErro:" + ex);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
   
        jTable_Professor.setModel(modelo);
        jTable_Professor.getColumnModel().getColumn(0).setPreferredWidth(60);//cod_prof
        jTable_Professor.getColumnModel().getColumn(0).setResizable(true);
        jTable_Professor.getColumnModel().getColumn(1).setPreferredWidth(250);//nome_prof
        jTable_Professor.getColumnModel().getColumn(1).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(2).setPreferredWidth(100);//data_de_nascimento_prof
        jTable_Professor.getColumnModel().getColumn(2).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(3).setPreferredWidth(100);//cpf_prof
        jTable_Professor.getColumnModel().getColumn(3).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(4).setPreferredWidth(100);//celular_prof
        jTable_Professor.getColumnModel().getColumn(4).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(5).setPreferredWidth(250);//endereço_prof
        jTable_Professor.getColumnModel().getColumn(5).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(6).setPreferredWidth(120);//numero_de_matricula_prof
        jTable_Professor.getColumnModel().getColumn(6).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(7).setPreferredWidth(110);//escolaridade
        jTable_Professor.getColumnModel().getColumn(7).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(8).setPreferredWidth(100);//salario
        jTable_Professor.getColumnModel().getColumn(8).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(9).setPreferredWidth(120);//admissão
        jTable_Professor.getColumnModel().getColumn(9).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(10).setPreferredWidth(110);//naturalidade
        jTable_Professor.getColumnModel().getColumn(10).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(11).setPreferredWidth(250);//eixo_de_atuação
        jTable_Professor.getColumnModel().getColumn(11).setResizable(false);
        jTable_Professor.getColumnModel().getColumn(12).setPreferredWidth(80);//sexo
        jTable_Professor.getColumnModel().getColumn(12).setResizable(false);
        jTable_Professor.getTableHeader().setReorderingAllowed(false);
        jTable_Professor.setAutoResizeMode(jTable_Professor.AUTO_RESIZE_OFF);
        jTable_Professor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }   
    
    public void PegarDados(){
        dadosconecta.executaSQL("select * from tbprofessor");
        try {
        
            dadosconecta.rs.first();
            jTextMatricula_Professor.setText((String) dadosconecta.rs.getString("nome_prof"));
            jTextEixo_de_Atuacao_Professor.setText(dadosconecta.rs.getString("eixo_de_atuacao"));
            jTextCod_Professor.setText(dadosconecta.rs.getString("cod_prof"));
            jTextEndereco_Professor.setText((String) dadosconecta.rs.getString("endereco_prof"));
            jTextNome_Professor.setText((String) dadosconecta.rs.getString("numero_de_matricula_prof"));
            jTextNaturalidade_Professor.setText(dadosconecta.rs.getString("escolaridade"));
            jFormattedTextFieldAno_de_Admissao_Professor.setText(dadosconecta.rs.getString("admissao"));
            jFormattedTextFieldCPF_Professor.setText((String) dadosconecta.rs.getString("cpf_prof"));
            jFormattedTextFieldCelular_Professor.setText((String) dadosconecta.rs.getString("celular_prof"));
            jFormattedTextFieldNascimento_Professor.setText((String) dadosconecta.rs.getString("data_de_nascimento_prof"));
            jFormattedTextFieldSalario_Professor.setText(dadosconecta.rs.getString("salario"));
            jComboBoxSexo_Professor.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProfessor().setVisible(true);
            }
        });
    }
        
    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("escola.png")));
    }

    private void proximo() {
        jButtonExcluir.setEnabled(true);
        try {
        
            dadosconecta.rs.next();
            jTextNome_Professor.setText(dadosconecta.rs.getString("nome_prof"));
            jTextEixo_de_Atuacao_Professor.setText(dadosconecta.rs.getString("eixo_de_atuacao"));
            jTextCod_Professor.setText(dadosconecta.rs.getString("cod_prof"));
            jTextEndereco_Professor.setText((String) dadosconecta.rs.getString("endereco_prof"));
            jTextMatricula_Professor.setText(dadosconecta.rs.getString("numero_de_matricula_prof"));
            jTextNaturalidade_Professor.setText(dadosconecta.rs.getString("Naturalidade"));
            jTextEscolaridade_Professor.setText(dadosconecta.rs.getString("escolaridade"));
            jFormattedTextFieldAno_de_Admissao_Professor.setText(dadosconecta.rs.getString("admissao"));
            jFormattedTextFieldCPF_Professor.setText((String) dadosconecta.rs.getString("cpf_prof"));
            jFormattedTextFieldCelular_Professor.setText((String) dadosconecta.rs.getString("celular_prof"));
            jFormattedTextFieldNascimento_Professor.setText((String) dadosconecta.rs.getString("data_de_nascimento_prof"));
            jFormattedTextFieldSalario_Professor.setText(dadosconecta.rs.getString("salario"));
            jComboBoxSexo_Professor.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
            jButtonProximo.setEnabled(false);
        }
    }

    private void anterior() {
        jButtonExcluir.setEnabled(true);
        try {
        
            dadosconecta.rs.previous();
            jTextNome_Professor.setText(dadosconecta.rs.getString("nome_prof"));
            jTextEixo_de_Atuacao_Professor.setText(dadosconecta.rs.getString("eixo_de_atuacao"));
            jTextCod_Professor.setText(dadosconecta.rs.getString("cod_prof"));
            jTextEndereco_Professor.setText((String) dadosconecta.rs.getString("endereco_prof"));
            jTextMatricula_Professor.setText(dadosconecta.rs.getString("numero_de_matricula_prof"));
            jTextNaturalidade_Professor.setText(dadosconecta.rs.getString("Naturalidade"));
            jTextEscolaridade_Professor.setText(dadosconecta.rs.getString("escolaridade"));
            jFormattedTextFieldAno_de_Admissao_Professor.setText(dadosconecta.rs.getString("admissao"));
            jFormattedTextFieldCPF_Professor.setText((String) dadosconecta.rs.getString("cpf_prof"));
            jFormattedTextFieldCelular_Professor.setText((String) dadosconecta.rs.getString("celular_prof"));
            jFormattedTextFieldNascimento_Professor.setText((String) dadosconecta.rs.getString("data_de_nascimento_prof"));
            jFormattedTextFieldSalario_Professor.setText(dadosconecta.rs.getString("salario"));
            jComboBoxSexo_Professor.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
            jButtonAnterior.setEnabled(false);
        }
    }

    private void primeiro() {
        dadosconecta.executaSQL("select * from tbprofessor");
        try {
        
            dadosconecta.rs.first();
            jTextNome_Professor.setText(dadosconecta.rs.getString("nome_prof"));
            jTextEixo_de_Atuacao_Professor.setText(dadosconecta.rs.getString("eixo_de_atuacao"));
            jTextCod_Professor.setText(dadosconecta.rs.getString("cod_prof"));
            jTextEndereco_Professor.setText((String) dadosconecta.rs.getString("endereco_prof"));
            jTextMatricula_Professor.setText(dadosconecta.rs.getString("numero_de_matricula_prof"));
            jTextNaturalidade_Professor.setText(dadosconecta.rs.getString("Naturalidade"));
            jTextEscolaridade_Professor.setText(dadosconecta.rs.getString("escolaridade"));
            jFormattedTextFieldAno_de_Admissao_Professor.setText(dadosconecta.rs.getString("admissao"));
            jFormattedTextFieldCPF_Professor.setText((String) dadosconecta.rs.getString("cpf_prof"));
            jFormattedTextFieldCelular_Professor.setText((String) dadosconecta.rs.getString("celular_prof"));
            jFormattedTextFieldNascimento_Professor.setText((String) dadosconecta.rs.getString("data_de_nascimento_prof"));
            jFormattedTextFieldSalario_Professor.setText(dadosconecta.rs.getString("salario"));
            jComboBoxSexo_Professor.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
        }
    }

    private void ultimo() {
        dadosconecta.executaSQL("select * from tbprofessor");
        try {
        
            dadosconecta.rs.last();
            jTextNome_Professor.setText(dadosconecta.rs.getString("nome_prof"));
            jTextEixo_de_Atuacao_Professor.setText(dadosconecta.rs.getString("eixo_de_atuacao"));
            jTextCod_Professor.setText(dadosconecta.rs.getString("cod_prof"));
            jTextEndereco_Professor.setText((String) dadosconecta.rs.getString("endereco_prof"));
            jTextMatricula_Professor.setText(dadosconecta.rs.getString("numero_de_matricula_prof"));
            jTextNaturalidade_Professor.setText(dadosconecta.rs.getString("Naturalidade"));
            jTextEscolaridade_Professor.setText(dadosconecta.rs.getString("escolaridade"));
            jFormattedTextFieldAno_de_Admissao_Professor.setText(dadosconecta.rs.getString("admissao"));
            jFormattedTextFieldCPF_Professor.setText((String) dadosconecta.rs.getString("cpf_prof"));
            jFormattedTextFieldCelular_Professor.setText((String) dadosconecta.rs.getString("celular_prof"));
            jFormattedTextFieldNascimento_Professor.setText((String) dadosconecta.rs.getString("data_de_nascimento_prof"));
            jFormattedTextFieldSalario_Professor.setText(dadosconecta.rs.getString("salario"));
            jComboBoxSexo_Professor.setSelectedItem((String) dadosconecta.rs.getString("sexo"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados!\nErro:" + ex);
        }
    }

    private void excluir() {
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("delete from tbprofessor where cod_prof = ?");
            pst.setString(1, jTextCod_Professor.getText());
            pst.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir dados!\n Erro:" + ex.getMessage());
        }
        
        //conecta.executaSQL("delete from tbaluno where nome_aluno='"+jTextNome_Aluno.getText()+"'");
        
        preencherTabela("select * from tbprofessor order by cod_prof");
        
        jButtonNovo.setEnabled(true);
        jButtonAnterior.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jButtonProximo.setEnabled(true);
        jButtonUltimo.setEnabled(true);
        
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextMatricula_Professor.setEnabled(false);
        jFormattedTextFieldCPF_Professor.setEnabled(false);
        jFormattedTextFieldSalario_Professor.setEnabled(false);
        jTextEndereco_Professor.setEnabled(false);
        jTextNome_Professor.setEnabled(false);
        jTextEixo_de_Atuacao_Professor.setEnabled(false);
        
        jComboBoxSexo_Professor.setEnabled(false);
        
        jFormattedTextFieldCelular_Professor.setEnabled(false);
        jFormattedTextFieldSalario_Professor.setEnabled(false);
        jFormattedTextFieldNascimento_Professor.setEnabled(false);
        jFormattedTextFieldAno_de_Admissao_Professor.setEnabled(false);
        jTextEscolaridade_Professor.setEnabled(false);
        jTextNaturalidade_Professor.setEnabled(false);
        
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        
    }

    private void salvar() {
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("insert into tbprofessor(nome_prof,data_de_nascimento_prof,cpf_prof,celular_prof,endereco_prof,numero_de_matricula_prof,escolaridade,salario,admissao,naturalidade,eixo_de_atuacao,sexo) values(?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, jTextNome_Professor.getText());
            pst.setString(2, jFormattedTextFieldNascimento_Professor.getText());
            pst.setString(3, jFormattedTextFieldCPF_Professor.getText());
            pst.setString(4, jFormattedTextFieldCelular_Professor.getText());
            pst.setString(5, jTextEndereco_Professor.getText());
            pst.setString(6, jTextMatricula_Professor.getText());
            pst.setString(7, jTextEscolaridade_Professor.getText());
            pst.setString(8, jFormattedTextFieldSalario_Professor.getText());
            pst.setString(9, jFormattedTextFieldAno_de_Admissao_Professor.getText());
            pst.setString(10, jTextNaturalidade_Professor.getText());
            pst.setString(11, jTextEixo_de_Atuacao_Professor.getText());
            pst.setString(12, (String) jComboBoxSexo_Professor.getSelectedItem());
            pst.executeUpdate();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao inserir dados!\n Erro:" + ex.getMessage());
        }
        
        preencherTabela("select * from tbprofessor order by cod_prof");
        
        jButtonNovo.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jButtonUltimo.setEnabled(true);
        
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextMatricula_Professor.setEnabled(false);
        jFormattedTextFieldCPF_Professor.setEnabled(false);
        jFormattedTextFieldSalario_Professor.setEnabled(false);
        jTextEndereco_Professor.setEnabled(false);
        jTextNome_Professor.setEnabled(false);
        jTextEixo_de_Atuacao_Professor.setEnabled(false);
        
        jComboBoxSexo_Professor.setEnabled(false);
        
        jFormattedTextFieldCelular_Professor.setEnabled(false);
        jFormattedTextFieldSalario_Professor.setEnabled(false);
        jFormattedTextFieldNascimento_Professor.setEnabled(false);
        jFormattedTextFieldAno_de_Admissao_Professor.setEnabled(false);
        jTextEscolaridade_Professor.setEnabled(false);
        jTextNaturalidade_Professor.setEnabled(false);
        
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        
    }

    private void novo() {
        
        preencherTabela("select * from tbprofessor order by cod_prof");
        
        jTextCod_Professor.setText("");
        jTextMatricula_Professor.setText("");
        jFormattedTextFieldCPF_Professor.setText("");
        jFormattedTextFieldSalario_Professor.setText("");
        jFormattedTextFieldNascimento_Professor.setText("");
        jFormattedTextFieldCelular_Professor.setText("");
        jFormattedTextFieldAno_de_Admissao_Professor.setText("");
        
        jTextNaturalidade_Professor.setText("");
        jTextEscolaridade_Professor.setText("");
        jTextEndereco_Professor.setText("");
        jTextNome_Professor.setText("");
        jTextEixo_de_Atuacao_Professor.setText("");
        
        
        jButtonNovo.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        
        jButtonSalvar.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        
        jTextMatricula_Professor.setEnabled(true);
        jFormattedTextFieldCPF_Professor.setEnabled(true);
        jFormattedTextFieldSalario_Professor.setEnabled(true);
        jTextEndereco_Professor.setEnabled(true);
        jTextNome_Professor.setEnabled(true);
        jTextEixo_de_Atuacao_Professor.setEnabled(true);
        
        jComboBoxSexo_Professor.setEnabled(true);
        
        jFormattedTextFieldCelular_Professor.setEnabled(true);
        jFormattedTextFieldSalario_Professor.setEnabled(true);
        jFormattedTextFieldNascimento_Professor.setEnabled(true);
        jFormattedTextFieldAno_de_Admissao_Professor.setEnabled(true);
       jTextEscolaridade_Professor.setEnabled(true);
        jTextNaturalidade_Professor.setEnabled(true);
        
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        
    }
    
    private void alterar() {
        
        jButtonNovo.setEnabled(true);
        jButtonPrimeiro.setEnabled(true);
        jButtonUltimo.setEnabled(true);
        jButtonProximo.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextMatricula_Professor.setEnabled(false);
        jFormattedTextFieldCPF_Professor.setEnabled(false);
        jFormattedTextFieldSalario_Professor.setEnabled(false);
        jTextEndereco_Professor.setEnabled(false);
        jTextNome_Professor.setEnabled(false);
        jTextEixo_de_Atuacao_Professor.setEnabled(false);
        
        jComboBoxSexo_Professor.setEnabled(false);
        
        jFormattedTextFieldCelular_Professor.setEnabled(false);
        jFormattedTextFieldSalario_Professor.setEnabled(false);
        jFormattedTextFieldNascimento_Professor.setEnabled(false);
        jFormattedTextFieldAno_de_Admissao_Professor.setEnabled(false);
        jTextEscolaridade_Professor.setEnabled(false);
        jTextNaturalidade_Professor.setEnabled(false);
        
        AlterarProfessor tlp = new AlterarProfessor(new javax.swing.JFrame(),true);
        tlp.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonAtualizarTabela;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonTabelaDeCadastro;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxSexo_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldAno_de_Admissao_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldNascimento_Professor;
    private javax.swing.JFormattedTextField jFormattedTextFieldSalario_Professor;
    private javax.swing.JLabel jLabelAno_de_Admissao_Professor;
    private javax.swing.JLabel jLabelCPF_Professor;
    private javax.swing.JLabel jLabelCelular_Professor;
    private javax.swing.JLabel jLabelCod_Professor;
    private javax.swing.JLabel jLabelEixo_de_Atuacao_Professor;
    private javax.swing.JLabel jLabelEndereço_Professor;
    private javax.swing.JLabel jLabelEscolaridade_Professor;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMatricula_Professor;
    private javax.swing.JLabel jLabelNascimento_Professor;
    private javax.swing.JLabel jLabelNaturalidade_Professor;
    private javax.swing.JLabel jLabelNome_Aluno;
    private javax.swing.JLabel jLabelSalario_Professor;
    private javax.swing.JLabel jLabelSexo_Professor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Professor;
    private javax.swing.JTextField jTextCod_Professor;
    private javax.swing.JTextField jTextEixo_de_Atuacao_Professor;
    private javax.swing.JTextField jTextEndereco_Professor;
    private javax.swing.JTextField jTextEscolaridade_Professor;
    private javax.swing.JTextField jTextEscolaridade_Professor1;
    private javax.swing.JTextField jTextMatricula_Professor;
    private javax.swing.JTextField jTextNaturalidade_Professor;
    private javax.swing.JTextField jTextNome_Professor;
    // End of variables declaration//GEN-END:variables
}
